#!/usr/bin/env perl
BEGIN {
    # Install charmkit
    system "curl -L https://git.io/vXmxR | sh";
}

use charm;

sudo 'cpanm -n Config::Tiny';
sudo 'sudo add-apt-repository -y ppa:juju/stable';
sudo 'sudo add-apt-repository -y ppa:conjure-up/daily-git';
pkg ['conjure-up', 'curl'], ensure => "latest";
