#!/usr/bin/env perl

use charm;

status "maintenance", "Configuring ZNC";

my $version_str = run 'znc --version | grep -P "^ZNC\s"';
$version_str =~ /^ZNC\s(\d\.\d\.\d.*)\s\-/;

run "application-version-set $1";

status 'active', 'Ready';
