#!/usr/bin/env perl

use charm;

status "maintenance", "Configuring ZNC";

my $version = run 'znc --version | grep -P "^ZNC\s"';
$version =~ /^ZNC\s(\d\.\d\.\d)/;
run "application-version-set $1";

status 'active', 'Ready';
